UNITY_IP = "127.0.0.1"
UNITY_PORT = 5005

CAMERA_INDEX = 0
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30

MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.5

HAND_UP_THRESHOLD = 0.09 
HANDS_TOGETHER_THRESHOLD = 0.10 
GRAB_FINGERS_THRESHOLD = 3  

DEBOUNCE_FRAMES = 4
GRAB_DEBOUNCE_FRAMES = 8
HIGHLIGHT_DEBOUNCE_FRAMES = 10   

SHOW_DEBUG_INFO = True
SHOW_LANDMARKS = True
DEBUG_WINDOW_NAME = "Clean Ocean VR - Gesture Control"

REDUCE_CPU_USAGE = True
FRAME_SKIP = 1